# set prefix to control-f
set -g prefix C-f

# vim like nav
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#unbind system defined prefix
unbind C-b

set -g mouse on
set-option -g allow-rename off

# True color settings
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",$TERM:Tc"

setw -g monitor-activity on
set -g visual-activity on

# index windows from 1
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-position bottom


set -g @tmux-dotbar-right false
# tokyonight
set -g @tmux-dotbar-bg "#24283b"           # Storm Background
set -g @tmux-dotbar-fg "#565f89"           # Inactive dots
set -g @tmux-dotbar-fg-current "#c0caf5"   # Active window
set -g @tmux-dotbar-fg-session "#9499b8"   # Session name
set -g @tmux-dotbar-fg-prefix "#bb9af7"    # Prefix indicator



run '~/.tmux/plugins/tpm/tpm'
